# ---------------- #
#   Main Configs   #
# ---------------- #
baseurl:
url: https://superhxf.github.io
date_format: "ordinal"
title: 希罗卡
subtitle: "代码改变人生"
description: "希罗卡的个人博客"
keywords: 希罗卡, 小卡, 郝晓飞,haoxiaofei
timezone: Asia/Shanghai
encoding: "utf-8"
side_bar_repo_limit: 5

# ---------------- #
#      Author      #
# ---------------- #
author: superhxf
organization: 
organization_url: 
github_username: superhxf
location: shanghai, China
email: 13466481949@163.com

# ---------------- #
#    Navigation    #
# ---------------- #
navs:
  -
    href: /
    label: 首页

  -
    href: /categories/
    label: 分类

  -
    href: /archives/
    label: 归档

  -
    href: /wiki/
    label: 维基

  -
    href: /links/
    label: 链接

  -
    href: /about/
    label: 关于

# ---------------- #
#       RSS        #
# ---------------- #
subscribe_rss: /feed.xml

# ---------------- #
#      Jekyll      #
# ---------------- #
markdown: kramdown
kramdown:
    input: GFM
highlighter: rouge
paginate: 10
lsi: false
quiet: false
excerpt_separator: "\n\n"
permalink: /:year/:month/:day/:title/
gems:
    - jekyll-github-metadata
    - rouge
#     - jekyll-html-pipeline
    - jekyll-paginate
    - jekyll-sitemap
    - jekyll-feed
    - jemoji
#     - jekyll-mentions
collections:
    wiki:
        output: true
        permalink: /wiki/:path/

repository: superhxf/superhxf.github.io

# ---------------- #
#      Comments    #
# ---------------- #
# support provider: disqus, gitment, gitalk
comments_provider: gitalk
# !!!重要!!! 请修改下面这些信息为你自己申请的
# !!!Important!!! Please modify infos below to yours
# https://disqus.com
disqus:
    username: 
# https://imsun.net/posts/gitment-introduction/
gitment:
    owner: superhxf
    repo: superhxf.github.io
    oauth:
        client_id: 627e8a20de668ff46335
        client_secret: e8ed4836303ea2076106029789598a12179931a2
# https://github.com/gitalk/gitalk#install
gitalk:
    owner: superhxf
    repo: superhxf.github.io
    clientID: 627e8a20de668ff46335
    clientSecret: e8ed4836303ea2076106029789598a12179931a2
# 在使用其它评论组件时可点击显示 Disqus
lazy_load_disqus : true

# ---------------- #
#      Search      #
# ---------------- #
simple_jekyll_search:
    # 是否支持全文搜索
    fulltext: true
    # 最多显示多少条搜索结果
    limit: 10

# # ---------------- #
# #    Analytics     #
# # ---------------- #
# google:
#     analytics_id: UA-80669434-1
